# Generated by Django 3.2.5 on 2021-08-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_compra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='version_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
