# Generated by Django 3.2.5 on 2021-08-03 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_alter_item_version_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='version_id',
        ),
    ]
