# Generated by Django 3.2.5 on 2021-08-01 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('bucket', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_url', models.CharField(max_length=100)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lojas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(max_length=100)),
                ('atual', models.BooleanField(default=False)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='estoque.foto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.FloatField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='estoque.loja')),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto'),
        ),
    ]
