# Generated by Django 3.2.5 on 2021-08-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='nome_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
